version: "3"

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # Observability
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    container_name: zipkin-all-in-one
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml", "" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus' metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  #my services
  file_persistence:
    container_name: file_persistence
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8081:8081"
    entrypoint: "java -javaagent:/home/docker/opentelemetry-javaagent.jar 
      -Dotel.service.name=file_persistence
      -Dotel.exporter.otlp.endpoint=http://otel-collector:4317 
      -Dotel.traces.exporter=otlp 
      -Dotel.metrics.exporter=otlp 
      -jar FilePersistence-0.0.1-SNAPSHOT.jar"
    depends_on:
      - otel-collector

  mf_analysis:
    container_name: mf_analysis
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    entrypoint: "java -javaagent:/home/docker/opentelemetry-javaagent.jar
      -Dotel.service.name=mf_analysis
      -Dotel.exporter.otlp.endpoint=http://otel-collector:4317
      -Dotel.traces.exporter=otlp
      -Dotel.metrics.exporter=otlp
      -Dspring.kafka.producer.bootstrap-servers=kafka:9092
      -Dfile_persistence_service=http://file_persistence:8081/save
      -jar MFAnalysis-0.0.1-SNAPSHOT.jar"
    depends_on:
      - otel-collector
      - kafka
      - file_persistence