receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  logging:
    logLevel: debug

processors:
  batch:

service:
  pipelines:

    metrics:
      receivers: [otlp]
      processors: [batch]
      #exporters: [logging]
      exporters: [prometheus]

    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      #exporters: [logging]
      exporters: [  jaeger ]