version: "2.1"

networks:
  telemetry_service:
    external: true
    name: my_network

services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all-in-one
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - telemetry_service

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml", "" ]
    stdin_open: true
    tty: true
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus' metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    networks:
      - telemetry_service

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - telemetry_service

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    volumes:
      - grafana_storage:/var/lib/grafana grafana/grafana-enterprise
    ports:
      - "3000:3000"
    networks:
      - telemetry_service

  #my services
  testservice:
    container_name: testservice
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    mem_limit: "1g"
    mem_reservation: "512m"
    entrypoint: "java 
      -Xmx10g
      -javaagent:/home/docker/opentelemetry-javaagent.jar
      -Dotel.service.name=test_service
      -Dotel.exporter.otlp.endpoint=http://otel-collector:4317
      -Dotel.traces.exporter=otlp
      -Dotel.metrics.exporter=otlp
      -Dservice1.url=http://testservice1:8081/
      -jar TestService-0.0.1-SNAPSHOT.jar"
    depends_on:
      - otel-collector
    networks:
      - telemetry_service

  testservice1:
    container_name: testservice1
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8081:8081"
    entrypoint: "java -javaagent:/home/docker/opentelemetry-javaagent.jar
      -Dotel.service.name=test_service1
      -Dotel.exporter.otlp.endpoint=http://otel-collector:4317
      -Dotel.traces.exporter=otlp
      -Dotel.metrics.exporter=otlp
      -jar TestService1-0.0.1-SNAPSHOT.jar"
    depends_on:
      - otel-collector
    networks:
      - telemetry_service

volumes:
  grafana_storage: