version: "3.7"

networks:
  my_bridge:

services:
  kafka:
    image: pod.kafka
    container_name: kafka.rohit.com
    build:
      context: ./kafka
      dockerfile: Dockerfile
    ports:
      - 9092:9092
    volumes:
      - /tmp/data/kafka:/tmp/data/kafka
    entrypoint:  "/home/kafka/scripts/start.sh"
    networks:
      my_bridge:

  kafka2:
    image: pod.kafka
    build:
      context: ./kafka
      dockerfile: Dockerfile
    volumes:
      - /tmp/data/kafka:/tmp/data/kafka
    command: "/bin/bash"
    tty: true
    stdin_open: true
    networks:
      my_bridge: